const STORAGE_KEY="fatima-cosmetique-stock-v2";
const demoProducts=[{id:"prod-1",name:"Creme visage eclat",category:"Soins visage",sku:"FC-001",purchasePrice:6.5,salePrice:12,stock:18,alertLevel:5},{id:"prod-2",name:"Huile capillaire",category:"Cheveux",sku:"FC-014",purchasePrice:4,salePrice:9.5,stock:7,alertLevel:4},{id:"prod-3",name:"Parfum vanille",category:"Parfum",sku:"FC-026",purchasePrice:8,salePrice:18,stock:3,alertLevel:5},{id:"prod-4",name:"Gloss rose",category:"Maquillage",sku:"FC-039",purchasePrice:2.25,salePrice:6,stock:22,alertLevel:6}];
const el={productForm:qs("#product-form"),productFormTitle:qs("#product-form-title"),productId:qs("#product-id"),productName:qs("#product-name"),productCategory:qs("#product-category"),productSku:qs("#product-sku"),purchasePrice:qs("#purchase-price"),salePrice:qs("#sale-price"),stockQuantity:qs("#stock-quantity"),alertLevel:qs("#alert-level"),saveProduct:qs("#save-product"),cancelEdit:qs("#cancel-edit"),searchProducts:qs("#search-products"),filterCategory:qs("#filter-category"),productsTable:qs("#products-table"),saleForm:qs("#sale-form"),saleProduct:qs("#sale-product"),saleQuantity:qs("#sale-quantity"),saleUnitPrice:qs("#sale-unit-price"),saleDate:qs("#sale-date"),salesTable:qs("#sales-table"),clearSales:qs("#clear-sales"),alertsList:qs("#alerts-list"),toast:qs("#toast"),totalProducts:qs("#total-products"),totalStock:qs("#total-stock"),totalSales:qs("#total-sales"),totalProfit:qs("#total-profit"),totalAlerts:qs("#total-alerts"),inventoryValue:qs("#inventory-value")};
let state=loadState();init();
function qs(s){return document.querySelector(s)}
function init(){el.saleDate.value=new Date().toISOString().slice(0,10);el.productForm.addEventListener("submit",saveProduct);el.productForm.addEventListener("reset",()=>setTimeout(resetProductForm,0));el.cancelEdit.addEventListener("click",resetProductForm);el.searchProducts.addEventListener("input",renderProducts);el.filterCategory.addEventListener("change",renderProducts);el.productsTable.addEventListener("click",handleProductAction);el.saleForm.addEventListener("submit",saveSale);el.saleProduct.addEventListener("change",fillSalePrice);el.clearSales.addEventListener("click",clearSales);renderAll()}
function loadState(){const fallback={products:demoProducts,sales:[]};try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!saved||!Array.isArray(saved.products)||!Array.isArray(saved.sales))return fallback;return{products:saved.products.map(normalizeProduct),sales:saved.sales.map(normalizeSale)}}catch(e){return fallback}}
function normalizeProduct(p){return{id:p.id||createId("prod"),name:String(p.name||"").trim(),category:String(p.category||"Autre").trim(),sku:String(p.sku||"").trim(),purchasePrice:toNumber(p.purchasePrice),salePrice:toNumber(p.salePrice),stock:toInteger(p.stock),alertLevel:toInteger(p.alertLevel)}}
function normalizeSale(s){return{id:s.id||createId("sale"),productId:s.productId||"",productName:s.productName||"Produit supprime",quantity:toInteger(s.quantity),unitPrice:toNumber(s.unitPrice),purchasePrice:toNumber(s.purchasePrice),total:toNumber(s.total),profit:toNumber(s.profit),date:s.date||new Date().toISOString().slice(0,10)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function saveProduct(e){e.preventDefault();const product={id:el.productId.value||createId("prod"),name:el.productName.value.trim(),category:el.productCategory.value,sku:el.productSku.value.trim()||createSku(),purchasePrice:toNumber(el.purchasePrice.value),salePrice:toNumber(el.salePrice.value),stock:toInteger(el.stockQuantity.value),alertLevel:toInteger(el.alertLevel.value)};if(!product.name||!product.category){showToast("Nom et categorie obligatoires.");return}if(product.salePrice<product.purchasePrice){showToast("Le prix de vente doit etre superieur au prix d'achat.");return}const i=state.products.findIndex(item=>item.id===product.id);if(i>=0){state.products[i]=product;showToast("Produit modifie.")}else{state.products.push(product);showToast("Produit ajoute.")}saveState();resetProductForm();renderAll()}
function editProduct(id){const p=findProduct(id);if(!p)return;el.productId.value=p.id;el.productName.value=p.name;el.productCategory.value=p.category;el.productSku.value=p.sku;el.purchasePrice.value=p.purchasePrice;el.salePrice.value=p.salePrice;el.stockQuantity.value=p.stock;el.alertLevel.value=p.alertLevel;el.productFormTitle.textContent="Modifier un produit";el.saveProduct.textContent="Modifier";el.cancelEdit.hidden=false;el.productForm.scrollIntoView({behavior:"smooth",block:"start"})}
function deleteProduct(id){const p=findProduct(id);if(!p)return;if(!window.confirm('Supprimer "'+p.name+'" du stock ?'))return;state.products=state.products.filter(item=>item.id!==id);saveState();resetProductForm();renderAll();showToast("Produit supprime.")}
function handleProductAction(e){const b=e.target.closest("button[data-action]");if(!b)return;if(b.dataset.action==="edit")editProduct(b.dataset.id);if(b.dataset.action==="delete")deleteProduct(b.dataset.id)}
function saveSale(e){e.preventDefault();const p=findProduct(el.saleProduct.value),q=toInteger(el.saleQuantity.value),unit=toNumber(el.saleUnitPrice.value),date=el.saleDate.value||new Date().toISOString().slice(0,10);if(!p){showToast("Choisis un produit.");return}if(q<1){showToast("La quantite doit etre au moins 1.");return}if(q>p.stock){showToast("Stock insuffisant pour cette vente.");return}state.sales.unshift({id:createId("sale"),productId:p.id,productName:p.name,quantity:q,unitPrice:unit,purchasePrice:p.purchasePrice,total:q*unit,profit:q*(unit-p.purchasePrice),date:date});p.stock-=q;saveState();el.saleForm.reset();el.saleDate.value=new Date().toISOString().slice(0,10);renderAll();showToast("Vente enregistree.")}
function clearSales(){if(!state.sales.length){showToast("Aucune vente a effacer.");return}if(!window.confirm("Effacer tout l'historique des ventes ?"))return;state.sales=[];saveState();renderAll();showToast("Historique efface.")}
function resetProductForm(){el.productForm.reset();el.productId.value="";el.productFormTitle.textContent="Ajouter un produit";el.saveProduct.textContent="Ajouter";el.cancelEdit.hidden=true}
function renderAll(){renderDashboard();renderCategoryFilter();renderProducts();renderSaleProducts();renderSales();renderAlerts()}
function renderDashboard(){const totals=state.products.reduce((a,p)=>{a.stock+=p.stock;a.value+=p.stock*p.purchasePrice;if(isLowStock(p))a.alerts+=1;return a},{stock:0,value:0,alerts:0});const salesTotal=state.sales.reduce((s,v)=>s+v.total,0),profitTotal=state.sales.reduce((s,v)=>s+v.profit,0);el.totalProducts.textContent=state.products.length;el.totalStock.textContent=totals.stock;el.totalSales.textContent=formatCurrency(salesTotal);el.totalProfit.textContent=formatCurrency(profitTotal);el.totalAlerts.textContent=totals.alerts;el.inventoryValue.textContent="Valeur stock: "+formatCurrency(totals.value)}
function renderCategoryFilter(){const current=el.filterCategory.value,cats=[...new Set(state.products.map(p=>p.category))].filter(Boolean).sort((a,b)=>a.localeCompare(b,"fr"));el.filterCategory.innerHTML='<option value="">Toutes les categories</option>';cats.forEach(c=>{const o=document.createElement("option");o.value=c;o.textContent=c;el.filterCategory.appendChild(o)});el.filterCategory.value=cats.includes(current)?current:""}
function renderProducts(){const query=el.searchProducts.value.trim().toLowerCase(),cat=el.filterCategory.value;const products=state.products.filter(p=>[p.name,p.category,p.sku].join(" ").toLowerCase().includes(query)&&(!cat||p.category===cat)).sort((a,b)=>a.name.localeCompare(b.name,"fr"));if(!products.length){el.productsTable.innerHTML='<tr><td colspan="7" class="empty-state">Aucun produit trouve.</td></tr>';return}el.productsTable.innerHTML=products.map(p=>{const st=getStockStatus(p);return '<tr><td><span class="product-name">'+escapeHtml(p.name)+'<small>Achat: '+formatCurrency(p.purchasePrice)+'</small></span></td><td>'+escapeHtml(p.category)+'</td><td>'+escapeHtml(p.sku)+'</td><td>'+formatCurrency(p.salePrice)+'</td><td>'+p.stock+'</td><td><span class="status '+st.className+'">'+st.label+'</span></td><td><div class="row-actions"><button class="button ghost" type="button" data-action="edit" data-id="'+p.id+'">Modifier</button><button class="button danger" type="button" data-action="delete" data-id="'+p.id+'">Supprimer</button></div></td></tr>'}).join("")}
function renderSaleProducts(){const current=el.saleProduct.value,products=state.products.filter(p=>p.stock>0).sort((a,b)=>a.name.localeCompare(b.name,"fr"));el.saleProduct.innerHTML='<option value="">Choisir un produit</option>';products.forEach(p=>{const o=document.createElement("option");o.value=p.id;o.textContent=p.name+" - stock "+p.stock;el.saleProduct.appendChild(o)});el.saleProduct.value=products.some(p=>p.id===current)?current:"";fillSalePrice()}
function renderSales(){if(!state.sales.length){el.salesTable.innerHTML='<tr><td colspan="5" class="empty-state">Aucune vente enregistree.</td></tr>';return}el.salesTable.innerHTML=state.sales.slice(0,25).map(s=>'<tr><td>'+formatDate(s.date)+'</td><td>'+escapeHtml(s.productName)+'</td><td>'+s.quantity+'</td><td>'+formatCurrency(s.total)+'</td><td>'+formatCurrency(s.profit)+'</td></tr>').join("")}
function renderAlerts(){const alerts=state.products.filter(isLowStock).sort((a,b)=>a.stock-b.stock);if(!alerts.length){el.alertsList.innerHTML='<div class="empty-state">Tous les stocks sont au-dessus des seuils.</div>';return}el.alertsList.innerHTML=alerts.map(p=>'<article class="alert-item '+(p.stock===0?'out':'')+'"><strong>'+escapeHtml(p.name)+'</strong><span>'+(p.stock===0?'Rupture de stock':'Stock faible: '+p.stock+' restant(s)')+'</span><span>Seuil: '+p.alertLevel+' · '+escapeHtml(p.category)+'</span></article>').join("")}
function fillSalePrice(){const p=findProduct(el.saleProduct.value);el.saleUnitPrice.value=p?p.salePrice:""}
function findProduct(id){return state.products.find(p=>p.id===id)}
function isLowStock(p){return p.stock<=p.alertLevel}
function getStockStatus(p){if(p.stock<=0)return{label:"Rupture",className:"out"};if(isLowStock(p))return{label:"Alerte",className:"low"};return{label:"OK",className:"ok"}}
function createSku(){return "FC-"+String(state.products.length+1).padStart(3,"0")}
function createId(prefix){return prefix+"-"+Date.now()+"-"+Math.random().toString(16).slice(2)}
function toNumber(v){const n=Number(v);return Number.isFinite(n)&&n>=0?n:0}
function toInteger(v){const n=parseInt(v,10);return Number.isFinite(n)&&n>=0?n:0}
function formatCurrency(v){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(toNumber(v))}
function formatDate(v){return new Intl.DateTimeFormat("fr-FR").format(new Date(v))}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function showToast(message){el.toast.textContent=message;el.toast.classList.add("show");window.clearTimeout(showToast.timeoutId);showToast.timeoutId=window.setTimeout(()=>el.toast.classList.remove("show"),2600)}
